on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: VITE_WSS_URL="wss://wss.knur.club" VITE_BACKEND_URL="https://api.knur.club"  VITE_FRONTEND_URL="https://mamm0n.knur.club" npm run build
      - name: Build, tag, and push image to Docker Hub
        id: build-image
        run: |
          docker login -u fvlvte -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -q -t fvlvte/knurobotfrontend:latest .
          docker push fvlvte/knurobotfrontend:latest
