on:
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - name: Install dependencies
        run: npm ci
      - name: Check linter
        run: npm run lint:prod
      - name: Check prettier
        run: npm run prettier:prod
      - name: Build
        run: >
          VITE_WSS_URL="wss://wss.knur.club"
          VITE_BACKEND_URL="https://api.knur.club" 
          VITE_FRONTEND_URL="https://mamm0n.knur.club" 
          npm run build
